### PR TITLE
Update for Stardew Valley 1.6

### LINKED ISSUE #3: Update to 1.6
### Describe the bug
Please give a quick description of the bug.

### Browser and OS
Please include which browser you are using (Chrome, Firefox, Safari, etc.) and its version. Also include which OS you are using (Windows, macOS, Android, iOS, etc.) and its version.

### Save file
Please include your save file in the issue if it is relevant.

### LINKED ISSUE #4: Will this work for after the Update 1.6?
Hello, I use this tool often but I used it for the first time today since the update and it didnt list the items and I got a lot of NaN codes in some of the sections. 

I am assuming the tool would have to be remade for the update, I do love it a lot so I was just curious if this was something you were planning to do? Or if I am mistaken and there is some other reason why it is not working for me. Thanks a bunch!

### PR DESCRIPTION
**Pull request by FlashyReese**
- Support Stardew Valley 1.6 Update (Closes #3 Closes #4)

image
_(very real Tent Kit)_

### CODE REVIEW

**Comment by gucci-on-fleek** [comment]
Merged, thanks!

The cache might take up to 24 hours to update, but you should be able to manually clear it in the “Storage” tab of the developer tools.

**Comment by FlashyReese** [comment]
The page still seems to be broken but I'm not sure why because it seems to work fine locally.

**Comment by WoodlandSkipper** [comment]
> The page still seems to be broken but I'm not sure why because it seems to work fine locally.

Hello! I tested this today on both Firefox and Chrome & found that [parse_xml](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/item-finder.js#L305-L309), when called on [requests[1]](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/item-finder.js#L179-L188) (aka [src/items-to-csv.xslt](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/items-to-csv.xslt)), returns a document fragment where the row separator variable is a simple space character instead of a newline character (sorry for the messy screenshot!):
Screenshot 2024-04-20 131203

I found that the version of items-to-csv.xslt that's requested by the site (https://gucci-on-fleek.github.io/Stardew-Valley-Item-Finder/dist/items-to-csv.xslt) differs from the version that can be downloaded directly from the source code (https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/items-to-csv.xslt) in that the former sets the row separator value to be "'\n'" instead of "'\&#xA;'".

That the files are different is not surprising as [the xml is minified as a build step](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/build.sh#L27-L29). It looks like the whitespace character is changed as a consequence of [minification](https://github.com/tdewolff/minify?tab=readme-ov-file#newlines-remain-in-minified-output).

It looks like this makes a difference, though, to how document is parsed from a string in [parse_xml](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/item-finder.js#L305-L309), when called on [requests[1]](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/item-finder.js#L179-L188) (aka [src/items-to-csv.xslt](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/cd7ac806af07bd51a6dd53e840707242aab22e8f/src/items-to-csv.xslt)).

I tinkered with the [demo page for minify](https://go.tacodewolff.nl/minify) to see if `--xml-keep-whitespace` would keep the original whitespace character in place, but no dice.

I'm not sure what the fix is here, but I thought I'd share my findings in case they're of use!

**Comment by gucci-on-fleek** [comment]
Yep, you're exactly correct @WoodlandSkipper; thanks for the debugging! It should be fixed now, but the caching is pretty aggressive so you'll either need to wait 24 hours or manually delete the cache from the developer tools.

The issue was that the build script uses `ubuntu-latest`, which pointed to Ubuntu 20.04 the last time that the build ran, but points to Ubuntu 22.04 now. With older versions, the minifier ignored the character entities, but the newer version expanded the newline character entity (which makes sense since `\n` is 1 byte and `&#xA;` is 5 bytes). Unfortunately for here, attribute whitespace normalization rules meant that the raw newline character was normalized away to nothing. 

Considering that it's been 2.5 years since I've ran any builds, I'm pretty surprised that this is the _only_ thing that was broken. (And looking through the `build.sh`, I have no idea why I didn't just use a `Makefile`.)

**Pull request merged**
